apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: {{ .Release.Namespace }}
  labels:
    app: tasky
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: tasky
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tasky-secret
                  key: MONGODB_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tasky-secret
                  key: SECRET_KEY
