apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.env.mongodbUri | quote }}
  SECRET_KEY: {{ .Values.env.secretKey | quote }}
