apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: tasky
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
